### ISSUE TITLE
Breaks on version switching from 2.3.0 to 2.3.1

### ISSUE THREAD

**Issue by surajmandalcell** [imyelo/docsify-pagination#8]
Works fine in version 2.3.0

Here's the log

```javascript
ReferenceError: B is not defined[Learn More]
docsify-pagination.min.js:1:4102
window.$docsify.plugins</<
https://unpkg.com/docsify-pagination@2.3.1/dist/docsify-pagination.min.js:1:4102
o
http://unpkg.com/docsify/lib/docsify.min.js:1:699
s
http://unpkg.com/docsify/lib/docsify.min.js:1:741
o
http://unpkg.com/docsify/lib/docsify.min.js:1:52345
je._renderMain/</<
http://unpkg.com/docsify/lib/docsify.min.js:1:52497
ye/<
http://unpkg.com/docsify/lib/docsify.min.js:1:41344
e
http://unpkg.com/docsify/lib/docsify.min.js:1:40872
ye
http://unpkg.com/docsify/lib/docsify.min.js:1:40772
je._renderMain/<
http://unpkg.com/docsify/lib/docsify.min.js:1:52430
o
http://unpkg.com/docsify/lib/docsify.min.js:1:609
s
http://unpkg.com/docsify/lib/docsify.min.js:1:741
je._renderMain
http://unpkg.com/docsify/lib/docsify.min.js:1:52234
e._fetch/<
http://unpkg.com/docsify/lib/docsify.min.js:1:53857
then/<
http://unpkg.com/docsify/lib/docsify.min.js:1:3098

```

**Comment by imyelo** [comment]
This was my serious mistake. Sorry to bother you and very thanks to your timely feedback.

**Comment by surajmandalcell** [comment]
No problem! Thanks for the super fast fix!

**Comment by surajmandalcell** [comment]
@imyelo btw can i ask you how did you put 'edit on github' in docsify? just a small snippet would be nice, cant understand where how to include it in my docs 
https://github.com/surajmandalcell/Gtk-Theming-Guide

**Comment by imyelo** [comment]
You might be interested in [njleonzhang/docsify-edit-on-github](https://github.com/njleonzhang/docsify-edit-on-github)?

**Comment by surajmandalcell** [comment]
@imyelo yes, i'm actually talking about that only xD
```javascript
EditOnGithubPlugin.create(docBase, docEditBase, title)
```
where do i put this?

**Comment by imyelo** [comment]
@surajmandalcell Ha! I see what you meant now.

Actually I didn't use this before. Have you ever try this: (which has been mentioned in the readme)
https://github.com/njleonzhang/vue-data-tables/blob/c88b916442efb192f66f63f2a27df5b0005641cc/docs/index.html#L88-L103

**Comment by imyelo** [comment]
@surajmandalcell BTW. I found the pagination plugin in [Gtk-Theming-Guide](https://gtkthemingguide.now.sh) was broken around topic ``Creating Icon Theme``.
The [empty line in _sidebar.md](https://github.com/surajmandalcell/Gtk-Theming-Guide/commit/ba5f96c35da32f56c0416b77df3614d859787840#diff-2318fd6ccee1e6884820eb550858e1b3L6) produce an extra `<p>` element, then the plugin broke. 

This should be fixed in [https://github.com/imyelo/docsify-pagination/commit/ff4a90a2b01bfa96f56f9bf258ea8d15da814205](https://github.com/imyelo/docsify-pagination/commit/ff4a90a2b01bfa96f56f9bf258ea8d15da814205) and v2.3.3. Hope it help.

**Comment by surajmandalcell** [comment]
Thanks!
